### ISSUE TITLE
enforce that Masonry matches the schema

### ISSUE THREAD

**Issue by afeld** [opencontrol/schemas#12]
Right now, (I think) there is nothing tying the Masonry code to the content in this repository, other than us being careful. Would be helpful to have Masonry tests that validate the schema is still being followed, or maybe better yet, generate the schema from code+comments.

/cc https://github.com/opencontrol/compliance-masonry/pull/143#discussion_r63704573

**Comment by pburkholder** [comment]
Masonry is using models for standards (and perhaps others) that don't match the schemas here. E.g. https://github.com/opencontrol/schemas#standards-documentation show standards are like this:

```
standards:
  C-2:
    name: User Access
    description: There is an affordance for managing access by...
```

but https://github.com/opencontrol/compliance-masonry/blob/master/models/standards.go#L14-L24 has only `name` and `family`
