### ISSUE TITLE
The component "satisfies" map type should accept a "references" property that accepts a sequence of URLs, etc

### ISSUE THREAD

**Issue by anweiss** [opencontrol/schemas#64]
For each control map under the `satifies` property, there should be a property called `references` that takes a sequence of `reference` maps with `name` and `url` properties. This helps to clean up any reference documentation for each control rather than having to include URLs in each control's narrative(s).

For example

```yaml
satisfies:
  - control_key: AC-1
    covered_by: []
    implementation_statuses:
      - implementation blah
    control_origins:
      - origin blah
    narrative:
      - key: a
        text: |
          Blah
    references:
      - name: 'My doc page'
        url: https://urltomydocpage
    standard_key: NIST-800-53
```
