### ISSUE TITLE
Creating implementation_status: not applicable

### ISSUE THREAD

**Issue by shawndwells** [opencontrol/schemas#71]
Having ``implementation_status`` express that a control is not applicable would be valuable. What is the process to update the schema? Should a PR be opened with the new enum, or something more?

https://github.com/opencontrol/schemas/blob/dada46ab481e49f864d0b9011af8f6590807cb80/opencontrol-component-kwalify-schema.yaml#L91
`````
          implementation_status:
            type: str
            enum:
              - partial
              - complete
              - planned
              - none
`````
